[build]
  command = "npm --prefix sovran-group-website run build"
  publish = "sovran-group-website/build"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
